echo a.txt;
time -f "%E" ./checker input/a.txt out/a_best.out;
echo;
echo b.txt;
time -f "%E" ./checker input/b.txt out/b_best.out;
echo;
echo c.txt;
time -f "%E" ./checker input/c.txt out/c_best.out;
echo;
echo d.txt;
time -f "%E" ./checker input/d.txt out/d_best.out;
echo;
echo e.txt;
time -f "%E" ./checker input/e.txt out/e_best.out;
echo;
echo f.txt;
time -f "%E" ./checker input/f.txt out/f_best.out;
echo;
echo blong.txt;
time -f "%E" ./checker input/blong.txt out/blong_best.out;
echo;
echo clong.txt;
time -f "%E" ./checker input/clong.txt out/clong_best.out;
echo;
echo dlong.txt;
time -f "%E" ./checker input/dlong.txt out/dlong_best.out;
